jobs:
  CI:
    secrets: inherit
    strategy:
      matrix:
        include:
        - jdk: 11
          os: ubuntu-latest
          profile: PostgreSQL-9
        - jdk: 11
          os: ubuntu-latest
          profile: PostgreSQL-10
        - jdk: 11
          os: ubuntu-latest
          profile: PostgreSQL-11
        - jdk: 11
          os: ubuntu-latest
          profile: MySQL-8.0
        - jdk: 11
          os: ubuntu-latest
          profile: MySQL-5.6
        - jdk: 11
          os: ubuntu-latest
          profile: MySQL-5.7
        - jdk: 11
          os: ubuntu-latest
          profile: MariaDB-10.4
        - jdk: 11
          os: ubuntu-latest
          profile: MSSQL-2017-latest
        - jdk: 11
          os: ubuntu-latest
          profile: MSSQL-2019-latest
        - jdk: 11
          os: ubuntu-latest
          profile: DB2-11.5
        - jdk: 11
          os: ubuntu-latest
          profile: SQL-templates
        - jdk: 17
          os: ubuntu-latest
          profile: PostgreSQL-11
        - jdk: 17
          os: ubuntu-latest
          profile: MySQL-5.7
        - jdk: 17
          os: ubuntu-latest
          profile: MariaDB-10.4
        - jdk: 17
          os: ubuntu-latest
          profile: MSSQL-2019-latest
        - jdk: 17
          os: ubuntu-latest
          profile: Oracle-23
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ github.event.pull_request.head.sha || github.ref_name }}
      deploy: ${{ matrix.jdk == '8' && matrix.os == 'ubuntu-latest' }}
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
      profile: ${{ matrix.profile }}
  Deploy:
    if: ${{ github.repository_owner == 'eclipse-vertx' && (github.event_name == 'push'
      || github.event_name == 'schedule') }}
    name: Deploy to OSSRH
    needs: CI
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.event.pull_request.head.sha || github.ref_name }}
      jdk: 11
name: vertx-sql-client (5.x)
on:
  repository_dispatch:
    types: trigger-ga___ci-5.x.yml
