env:
  VERTX_NEXUS_PASSWORD: ${{ secrets.VERTX_NEXUS_PASSWORD }}
  VERTX_NEXUS_USERNAME: ${{ secrets.VERTX_NEXUS_USERNAME }}
jobs:
  Deploy:
    name: Deploy to OSSRH
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
    - continue-on-error: true
      name: Install JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ inputs.jdk }}
    - continue-on-error: true
      name: Get project version
      run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate
        -Dexpression=project.version -B | grep -v '\[')" >> $GITHUB_ENV
    - continue-on-error: true
      if: ${{ endsWith(env.PROJECT_VERSION, '-SNAPSHOT') }}
      name: Maven deploy
      run: mvn deploy -s .github/maven-cd-settings.xml -DskipTests -B -pl vertx-sql-client,vertx-pg-client,vertx-mysql-client,vertx-mssql-client,vertx-db2-client,vertx-sql-client-templates
  Deploy-Oracle:
    name: Deploy (Oracle) to OSSRH
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
    - continue-on-error: true
      name: Install JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Get project version
      run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate
        -Dexpression=project.version -B | grep -v '\[')" >> $GITHUB_ENV
    - continue-on-error: true
      if: ${{ endsWith(env.PROJECT_VERSION, '-SNAPSHOT') }}
      name: Maven deploy
      run: mvn deploy -s .github/maven-cd-settings.xml -DskipTests -B -pl vertx-oracle-client
name: Deploy
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
